name: deploy react

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t domdom10/ci_test -f Dockerfile.dev .
      - run: docker run -e CI=true domdom10/ci_test npm run test


      #shit here we go againddddd

